application:
  admin:
    username: ${SUPER_USER_USERNAME}
    password: ${SUPER_USER_PASSWORD}
    fullName: ${SUPER_USER_FULL_NAME}
    email: ${SUPER_USER_EMAIL}
  security:
    jwt:
      secretKey: ${JWT_SECRET}
      accessTokenExpiration: ${JWT_ACCESS_EXPIRATION}
      refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION}

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER}

spring:
  application:
    name: ${APPLICATION_NAME}
    version: ${APPLICATION_VERSION}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # data:
  #   redis:
  #     host: ${SPRING_REDIS_HOST}
  #     port: ${SPRING_REDIS_PORT}
  #     password: ${SPRING_REDIS_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  task:
    execution:
      pool:
        core-size: ${THREAD_POOL_CORE_SIZE}
        max-size: ${THREAD_POOL_MAX_SIZE}
        queue-capacity: ${THREAD_POOL_QUEUE_CAPACITY}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  # kafka:
  #   bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  #   consumer:
  #     group-id: ${KAFKA_CONSUMER_GROUP_ID}
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  swagger-ui:
    path: /docs
    default-model-expand-depth: 0
    defaultModelsExpandDepth: 0
    tags-sorter: alpha

server:
  port: ${PORT}
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS}
      max-queue-capacity: ${TOMCAT_MAX_QUEUE_CAPACITY}